version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: tombartuzel
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ce4teacher
    ports:
      - "5432:5432"
  backend:
    build: backend
    ports:
      - "3000:3000"
    volumes:
      - .:/backend/app
    depends_on:
      - db
  web:
    build: frontend
    ports:
      - "4200:4200"
    volumes:
      - .:/frontend/app
    depends_on:
      - backend
