name: Run Docker Compose
on:
  push:
    branches:
      - main

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get -y install docker-compose
    - name: Build and run containers
      run: |
        docker-compose up
