name: Build and run Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and run containers
        run: |
          docker-compose up --build -d
          docker-compose ps
      - name: Wait for containers to start and become healthy
        run: |
          docker-compose ps -q | xargs docker inspect --format '{{.State.Health.Status}}' | grep -q healthy
      - name: Stop containers
        run: docker-compose down
